/**
 * AREA: voice-safety-a11y
 * Screen copy, the Debate night event, accommodation retention, and the student care inbox.
 * Called from scripts/seed.mjs after the Milestone 1 batch. Admin SDK bypasses rules.
 * deleteAt matches src/voice/retention.ts: event end + 30 days.
 */
const DAY = 24 * 60 * 60 * 1000;
const accommodationDeleteAt = (eventEndMs) => eventEndMs + 30 * DAY;

export async function seedVoiceSafety(db, Timestamp, morning) {
  const eventEnd = Date.parse("2026-10-16T15:00:00Z");
  const deleteAt = accommodationDeleteAt(eventEnd);
  const batch = db.batch();
  const set = (path, data) => batch.set(db.doc(path), data);

  set("events/debate-night", {
    title: "Debate night",
    chip: "Circle event",
    hostLine: "Debate Circle · approved by Student Affairs",
    when: "Thu 16 Oct · 4:00–6:00 PM",
    whenSub: "Add to calendar",
    place: "Hall B · Building C, 2nd floor",
    placeSub: "Lift and ramp at the entrance",
    status: "published",
    hostType: "circle",
    hostId: "debate",
    end: Timestamp.fromMillis(eventEnd),
    access: [
      { title: "Step-free access", body: "Lift to 2nd floor · ramp at Building C entrance" },
      { title: "Quiet room nearby", body: "Room 203 · open during the event" },
      { title: "Captions & slides", body: "Live captions on screen · slides shared after" },
    ],
  });

  const nodeStart = Timestamp.fromMillis(Date.now() - 60 * 60 * 1000);
  const nodeEnd = Timestamp.fromMillis(Date.now() + 8 * 60 * 60 * 1000);
  set("events/robotics-build", {
    title: "Robotics Build Night",
    status: "published",
    hostType: "circle",
    hostId: "robotics",
    hostLabel: "Robotics Society",
    verified: true,
    kicker: "Circle event",
    meta: "Faculty of Engineering · Hope Node",
    place: "Faculty of Engineering",
    when: "Today · Faculty of Engineering",
    window: "6–9 PM",
    description: "Build a line-following robot with the team. Mentors on site, all levels welcome.",
    screenDescription: "Build a line-following robot with the team. Mentors on site, all levels welcome.",
    venueStatus: "approved",
    venueId: "engineering",
    nodeId: "engineering",
    checkIn: true,
    startsAt: nodeStart,
    endsAt: nodeEnd,
    end: nodeEnd,
    order: 4,
  });

  set("accommodations/debate-fig", {
    uid: "fig",
    nickname: "Quiet Fig",
    eventId: "debate-night",
    needs: ["seat_near_exit", "quiet_space"],
    note: "I’d like to sit near the door if possible.",
    status: "requested",
    createdAt: Timestamp.fromMillis(morning),
    deleteAt: Timestamp.fromMillis(deleteAt),
  });

  set("accommodations/robotics-maple", {
    uid: "maple",
    nickname: "Soft Maple",
    eventId: "robotics-build",
    needs: ["captions"],
    note: "",
    status: "arranged",
    createdAt: Timestamp.fromMillis(morning - DAY),
    arrangedBy: "sa-lina",
    arrangedAt: Timestamp.fromMillis(morning),
    deleteAt: Timestamp.fromMillis(accommodationDeleteAt(morning + 10 * DAY)),
  });

  set("cases/care-fig", {
    source: "care_signal",
    nickname: "Quiet Fig",
    careLevel: "needs_care",
    careCounts: { heavyCheckins: "4 of 6", declinedSupport: 3, lowVoice: 2 },
    stepsDone: ["extra_card", "next_day_checkin"],
    ladderStep: 2,
    status: "open",
  });

  set("careInbox/cedar/messages/note", {
    from: "counselor",
    nickname: "Quiet Cedar",
    eyebrow: "A note for Quiet Cedar",
    text: "A counselor noticed you’ve had a heavy week. They don’t know who you are.",
    quote: "Hi, I’m here if you want to talk, about exams or anything else. No pressure to reply.",
    timeLabel: "Today, 10:15 AM",
    at: Timestamp.fromMillis(morning),
  });

  set("voiceSafety/bundle", {
    screens: {
      offer: {
        title: "Daily check-in",
        when: "Tuesday · 9:12 PM",
        question: "How does right now feel?",
        moods: ["Heavy", "Tired", "Okay", "Lighter", "Good"],
        selected: "Heavy",
        offerTitle: "Want to tell us how you feel out loud?",
        offerBody: "Fifteen to thirty seconds. This reads tone signals on your phone, then deletes the recording.",
        speak: "Speak",
        typeInstead: "Type instead",
        skip: "Skip",
        footer: "Voice check-ins are on · change in Settings",
        misread: "Tone signals can miss different ways of speaking. Typing counts the same.",
      },
      recording: {
        title: "Voice check-in",
        eyebrow: "Listening",
        question: "What’s weighing on you\nright now?",
        time: "0:12",
        total: "0:30",
        progress: 0.4,
        hint: "At least 15 seconds. It stops at 30.",
        done: "I’m done",
        footer: "This reads tone signals on your phone. It does not detect emotion. The recording is deleted right after.",
      },
      result: {
        title: "Your check-in",
        petal: "+1 petal for showing up",
        heavyTitle: "The tone signals read tense.",
        okayTitle: "The tone signals read calm.",
        lighterTitle: "The tone signals read calm.",
        veryLowTitle: "The tone signals read low.",
        heavyBody: "This reads tone signals on your phone. It does not detect emotion. Loudness was unsteady.",
        okayBody: "This reads tone signals on your phone. It does not detect emotion.",
        lighterBody: "This reads tone signals on your phone. It does not detect emotion. The level stayed steady.",
        suggestions: [
          { title: "Breathe for two minutes", sub: "In for 4 · out for 6", href: "/breathe" },
          { title: "Say hi to your Exam Week Circle", sub: "3 people are studying now", href: "/circle/exam-week/chat" },
          { title: "Talk to a counselor", sub: "Anonymous · nickname only", href: "/support" },
        ],
        primary: "Start breathing",
        skip: "Not now, I’m okay",
        footer: "Only you see this. The recording is already deleted.",
      },
      supportFirst: {
        title: "You’re not alone",
        titlePlain: "Help is here",
        body: "The tone signals read low. This card is only for you; nothing was uploaded.",
        bodyPlain: "This is only on your phone. Nobody else heard it.",
        explain: "Nothing is sent unless you tap Share.",
        primary: "Talk to a counselor anonymously",
        primarySub: "They’ll see your nickname, not your name.",
        callTitle: "Call Embrace 1564",
        callSub: "Free, 24/7, confidential",
        breatheTitle: "Breathe for one minute",
        breatheSub: "In for 4 · out for 6",
        shareTitle: "Share with Student Affairs",
        shareSub: "Only if you choose · you pick what they see",
        skip: "Not now, I’m okay",
        reflection: "Show my reflection",
        footer: "Nothing is sent to Student Affairs unless you tap Share.",
      },
      voiceSheet: {
        title: "Voice check-ins",
        body: "When a daily check-in looks heavy, NABT can listen for 15–30 seconds. It reads tone signals on your phone. It does not detect emotion.",
        toggle: "Voice check-ins",
        toggleSub: "Off by default · you choose",
        points: [
          "Reads tone signals on your phone. The recording is deleted right after.",
          "Never sent to Student Affairs unless you tap Share.",
          "Calls are never analysed, in any chat.",
          "Only feeds your own plant and suggestions.",
        ],
        care: "How care signals work",
        careSub: "What leaves your phone, and what never does",
        on: "Turn on voice check-ins",
        off: "Turn off voice check-ins",
        skip: "Not now",
      },
      supportCard: {
        title: "You’re not alone",
        titlePlain: "Help is here",
        body: "That sounded heavy. This card is only for you; nobody else saw it.",
        bodyPlain: "This card is only on your phone. Nobody else saw it.",
        explain: "A counselor sees your nickname only if you choose to talk.",
        primary: "Talk to a counselor anonymously",
        primarySub: "They’ll see your nickname, not your name.",
        callTitle: "Call Embrace 1564",
        callSub: "Free, 24/7, confidential",
        breatheTitle: "Breathe for one minute",
        breatheSub: "In for 4 · out for 6",
        shareTitle: "Share with Student Affairs",
        shareSub: "Optional · you choose what they see",
        skip: "Not now, I’m okay",
      },
      outreach: {
        title: "Student Affairs (counselor)",
        chip: "Verified",
        note: "They don’t know who you are. You can share your name if you want.",
        day: "Today",
        who: "Student Affairs (counselor) · 11:20",
        messages: [
          "Hi Quiet Fig, I’m a counselor at Student Affairs. I saw things feel heavy right now. I’m here if you want to talk, here or in person. No pressure.",
          "Would it help if I shared a quiet room you can use this afternoon?",
        ],
        ask: "Share your name with Student Affairs?",
        askBody: "Only the counselor will see it, and it shows in your Privacy log. You can say no.",
        share: "Share",
        skip: "Not now",
        reply: "Reply as Quiet Fig…",
      },
      share: {
        title: "Share this message with Student Affairs?",
        body: "Only this message is sent. A counselor can reach out to your nickname.",
        label: "What they’ll see",
        quote: "I can’t keep doing this, nothing I do is enough anymore.",
        from: "From Quiet Fig · Exam Week circle · 11:02",
        foot: "Your name and ID stay hidden. The rest of the chat stays private.",
        primary: "Share with Student Affairs",
        skip: "Not now",
        peer: "Same. I just need to get through Thursday.",
      },
      gentleChat: {
        only: "Only you can see this",
        title: "How are you doing now?",
        body: "Yesterday sounded heavy. No pressure to answer.",
        better: "A bit better",
        heavy: "Still heavy",
        call: "Embrace 1564 · free, 24/7",
        sent: "Sent at 6:00 PM · outside your quiet hours",
        peer: "Good luck everyone tomorrow",
      },
      identity: {
        sub: "Verified · they don’t know who you are",
        bubble: "Would you be okay sharing your name with me, so I can check in with you in person?",
        title: "Share your identity with Student Affairs?",
        body: "A counselor asked. It’s your choice, and saying no changes nothing about the help you get.",
        label: "They will see",
        nameLabel: "Real name",
        idLabel: "ID number",
        foot: "Only the counselor sees it. It’s logged in your Privacy log.",
        explain: "Your name leaves the phone only if you tap Share my identity.",
        primary: "Share my identity",
        skip: "Not now",
      },
      declined: {
        note: "They don’t know who you are. You can share your name later if you want.",
        bubble: "Would you be okay sharing your name with me, so I can check in with you in person?",
        sys: "You chose not to share. That’s okay.",
        reply: "Thank you for telling me. I’m still here, right in this chat, whenever you want.",
        mine: "Thanks. Maybe later.",
        saved: "Your choice is saved",
        savedBody: "Nothing was shared. You can still talk here anonymously, or call Embrace 1564 anytime.",
        composer: "Reply as Quiet Fig…",
      },
      chatCard: {
        only: "Only you can see this",
        title: "Want to talk?",
        titlePlain: "Do you want help?",
        body: "That sounded heavy. Help is close, and nobody in this circle was told.",
        bodyPlain: "This note is only for you. The Circle was not told.",
        explain: "Talking to a counselor shares your nickname, not your name.",
        primary: "Talk to a counselor anonymously",
        call: "Call Embrace 1564",
        share: "Share this message",
        skip: "I’m okay, hide this",
        peer: "Anyone else stuck on Signals ch. 7?",
        mine: "I can’t keep doing this, nothing I do is enough anymore.",
        composer: "Share with your circle…",
      },
      careCase: {
        title: "Care signal",
        chip: "No content",
        nickname: "Quiet Fig",
        initial: "Q",
        meta: "Identity hidden · signal from the student’s phone · Oct 7, 8:40 AM",
        levelLabel: "Care level",
        levels: ["Gentle watch", "Needs care", "Reach out now"],
        active: 1,
        why: "Why, in plain words",
        reasons: [
          "Heavy check-ins 4 of the last 6 days",
          "Declined support 3 times",
          "Voice check-ins low twice",
        ],
        stepsLabel: "Softer steps so far",
        steps: [
          { title: "Extra support card shown", sub: "On the phone · Oct 5", state: "done" },
          { title: "Next-day gentle check-in", sub: "On the phone · Oct 6 · not answered", state: "done" },
          { title: "Reach out anonymously", sub: "Ladder step 2 · you write to the nickname", state: "now" },
        ],
        foot: "No score, recording or message left the phone.",
        primary: "Reach out anonymously",
      },
      careGentle: {
        greeting: "Morning, Cedar",
        eyebrow: "A small check-in",
        title: "Yesterday felt heavy.\nHow are you doing today?",
        moods: ["A bit better", "About the same", "Still heavy"],
        selected: "About the same",
        save: "Save",
        skip: "Not now, I’m okay",
        callTitle: "Embrace 1564",
        callSub: "Free, 24/7 · if it’s more than heavy",
        call: "Call",
        foot: "Only on your phone. Answering is always optional.",
      },
      careMessage: {
        title: "Student Affairs",
        sub: "Counselor · verified staff",
        chip: "You stay anonymous",
        sawLabel: "What they saw",
        saw: "Only that your phone sent a “needs care” signal. No check-ins, recordings, messages or name.",
        reply: "Reply",
        skip: "Not now",
        foot: "Sharing who you are is always your choice.",
      },
      careExplainer: {
        title: "How care signals work",
        lead: "Your phone notices when a week looks heavy, so help can find you without anyone reading anything.",
        onPhone: "On your phone",
        steps: [
          { title: "Notices patterns", sub: "Heavy check-ins, very low voice check-ins, declining support often", state: "done" },
          { title: "Tries softer steps first", sub: "An extra support card, then a gentle check-in next day", state: "done" },
          { title: "Then, only if it continues", sub: "Sends one “needs care” signal so a counselor can reach out anonymously", state: "now" },
        ],
        leaves: "What leaves your phone",
        leavesBody: "One signal: “needs care”. Nothing else.",
        never: "What never leaves",
        neverBody: "Recordings, check-in answers, messages, your name. There is never a score, for anyone. Calls are never analysed.",
        danger: "In immediate danger, NABT skips the steps and shows a support card with Embrace 1564 right away.",
        done: "Got it",
      },
      plainCheckin: {
        title: "Daily check-in",
        when: "Tuesday · 9:12 PM",
        question: "How do you feel right now?",
        explain: "Pick the one closest to how you feel. There is no right answer. Only you see it.",
        moods: ["Heavy", "Tired", "Okay", "Lighter", "Good"],
        selected: "Okay",
        note: "Same 5 choices, same order, every day. No timer.",
        add: "Want to add a word?",
        addSub: "Optional. Type or speak.",
        save: "Save check-in",
        skip: "Skip today",
      },
      nodePhoto: {
        place: "Faculty of Engineering",
        kicker: "Photo time · when you’re ready",
        quote: "You’re allowed to rest before you’ve earned it.",
        author: "Quiet Cedar",
        hint: "Take your time.\nNo countdown.",
        take: "Take photo",
        skip: "Skip photo",
        clock: "1:12 PM",
      },
      quiet: {
        banner: "You’re reading quietly",
        bannerSub: "Others don’t see you typing or when you’ve read. Say hi whenever you like.",
        starters: ["Hi, I’m new here", "Can I just listen?", "Thanks for sharing"],
        placeholder: "Share with your circle…",
      },
      accommodation: {
        title: "Request an accommodation",
        body: "Pick what would help. You don’t need to explain why.",
        needs: [
          { id: "seat_near_exit", label: "Seat near an exit" },
          { id: "quiet_space", label: "Quiet space" },
          { id: "captions", label: "Captions" },
          { id: "extra_time", label: "Extra time" },
          { id: "other", label: "Other" },
        ],
        selected: ["seat_near_exit", "quiet_space"],
        noteLabel: "Short note · optional",
        note: "I’d like to sit near the door if possible.",
        foot: "Only Student Affairs sees this. The host Circle doesn’t.",
        send: "Send",
        going: "I’m going",
        ask: "Request an accommodation, privately",
      },
      saAccommodation: {
        brand: "Student Affairs",
        heading: "Events",
        chip: "2 requests",
        foot: "Nickname only. Hosts never see accommodation requests.",
        arranged: "Arranged ✓",
        mark: "Mark arranged",
        message: "Message Quiet Fig",
        requested: "Requested",
        noteLabel: "Note",
        hint: "Room 203 is free as a quiet room 4–6 PM.",
        rows: [
          {
            initial: "Q",
            nickname: "Quiet Fig",
            when: "12 min ago",
            title: "Debate night · Thu 16 Oct · Hall B",
            needs: ["Seat near an exit", "Quiet space"],
            note: "I’d like to sit near the door if possible.",
            status: "requested",
          },
          {
            initial: "S",
            nickname: "Soft Maple",
            when: "Yesterday",
            title: "Robotics Build Night · Captions",
            needs: ["Captions"],
            note: "",
            status: "arranged",
          },
        ],
      },
    },
  });

  await batch.commit();
  await db.doc("users/cedar/settings/main").set({ voiceCheckins: false }, { merge: true });
}
