import { TONE_COPY } from "./signals";

export const voiceCopy = {
  offer: {
    title: "Daily check-in",
    when: "Right now",
    question: "How does right now feel?",
    moods: ["Heavy", "Tired", "Okay", "Lighter", "Good"],
    selected: "Heavy",
    offerTitle: "Want to say it out loud?",
    offerBody: "Fifteen to thirty seconds. This reads tone signals on your phone, then deletes the recording.",
    speak: "Speak",
    typeInstead: "Type instead",
    skip: "Skip",
    footer: "Voice check-ins are on · change in Settings",
    misread: "Tone signals can miss different ways of speaking. Typing counts the same.",
  },
  recording: {
    title: "Voice check-in",
    eyebrow: "Listening",
    question: "What’s weighing on you\nright now?",
    hint: "At least 15 seconds. It stops at 30.",
    done: "I’m done",
    footer: `${TONE_COPY} The recording is deleted right after.`,
  },
  result: {
    title: "Your check-in",
    petal: "+1 petal for showing up",
    primary: "Start breathing",
    skip: "Not now, I’m okay",
    footer: "Only you see this. The recording is already deleted.",
    suggestions: [
      { title: "Breathe for two minutes", sub: "In for 4 · out for 6", href: "/breathe" },
      { title: "Say hi to your Circle", sub: "A quiet hello is enough", href: "/chats" },
      { title: "Talk to a counselor", sub: "Anonymous · nickname only", href: "/support" },
    ],
  },
  support: {
    title: "You’re not alone",
    titlePlain: "Help is here",
    body: "The tone signals read low. This card is only for you; nothing was uploaded.",
    bodyPlain: "This is only on your phone. Nobody else heard it.",
    explain: "Nothing is sent unless you tap Share.",
    primary: "Talk to a counselor anonymously",
    primarySub: "They’ll see your nickname, not your name.",
    callTitle: "Call Embrace 1564",
    callSub: "Free, 24/7, confidential",
    breatheTitle: "Breathe for one minute",
    breatheSub: "In for 4 · out for 4",
    shareTitle: "Share with Student Affairs",
    shareSub: "Only if you choose · you pick what they see",
    skip: "Not now, I’m okay",
    reflection: "Show my reflection",
    footer: "Nothing is sent to Student Affairs unless you tap Share.",
  },
  sheet: {
    title: "Voice check-ins",
    body: "When a daily check-in looks heavy, NABT can listen for 15–30 seconds. It reads tone signals on your phone. It does not detect emotion.",
    toggle: "Voice check-ins",
    toggleSub: "Off by default · you choose",
    points: [
      "Reads tone signals on your phone. The recording is deleted right after.",
      "Never sent to Student Affairs unless you tap Share.",
      "Calls are never analysed, in any chat.",
      "Only feeds your own plant and suggestions.",
    ],
    care: "How care signals work",
    careSub: "What leaves your phone, and what never does",
    on: "Turn on voice check-ins",
    off: "Turn off voice check-ins",
    skip: "Not now",
  },
};
